Zalando
BeAPI/shoppingfeed-for-woocommerce pull request #17
Opened 2021-11-26 16:57 UTC by stephane-gillot

les tests dans is_zalando sont différents des autres is_amazon .... parce que c'est dynamique

2021-11-26 17:18 UTC, Dacobah commented on src/Addons/Marketplace.php
> +			( 0 === strpos( $name, 'zalando' ) ) &&
- force la vérification de la chaine en `uppercase` VS "ZALANDO"
- `strpos` ne pose pas assez de contrôles : vérifie via un `substr` plutôt pour t'assurer que la chaine est bien dans les 7 premiers caractères

2021-11-26 17:18 UTC, Dacobah commented on src/Addons/Marketplace.php
> +			( 'zalando' . $id === $name )
A faire dès le premier contrôle (en même temps). Et donc plus besoin de `&&`

2022-04-27 10:26 UTC, jeremykervran approved these changes

2022-04-27 10:35 UTC, Rahe requested changes

2022-04-27 10:35 UTC, Rahe commented on src/Addons/Marketplace.php
> +	private function is_zalando( $sf_order ) {
PHP DOC à minima

2022-05-03 10:13 UTC, petitphp approved these changes

2022-05-03 10:15 UTC, merged