Put back weight as attribute for variations
BeAPI/shoppingfeed-for-woocommerce pull request #49
Opened 2022-08-05 14:55 UTC by jeremykervran

2022-08-08 10:50 UTC, petitphp requested changes
Je ne suis pas certain que ce soit à cette endroit qu'il faille ajouter le poids. Je regarderais plutôt dans la partie feed https://github.com/BeAPI/shoppingfeed-for-woocommerce/blob/master/src/Feed/Generator.php#L191

Pour la partie readme j'ai laissé des commentaires.

2022-08-08 10:50 UTC, petitphp commented on src/Admin/WoocommerceFilters.php
> +	public function sf_extra_attributes() {
Pourquoi le poids des variations est dans les attributs et pas à la racine comme pour les produits simple ?

2022-08-08 10:50 UTC, petitphp commented on readme.txt
> -```php
Il ne faut pas supprimer les backticks, juste le "php"
```
Avant : ```php
Après : ```
```

2022-08-08 10:50 UTC, petitphp commented on readme.txt
> -```
Ne pas supprimer.

2022-08-09 08:44 UTC, jeremykervran commented on src/Admin/WoocommerceFilters.php
> +	public function sf_extra_attributes() {
Validé avec SF, il faut que ça reste dans les attributs

2022-08-09 08:45 UTC, petitphp commented on src/Admin/WoocommerceFilters.php
> +	public function sf_extra_attributes() {
Ok.

2022-08-09 09:01 UTC, stephane-gillot approved these changes

2022-08-09 09:04 UTC, merged