set wakeup method to public & throw exception
BeAPI/shoppingfeed-for-woocommerce pull request #53
Opened 2022-08-24 15:15 UTC by f2cmbeapi

2022-08-25 07:41 UTC, petitphp requested changes

2022-08-25 07:41 UTC, petitphp commented on shoppingfeed.php
> + * Version:         6.1.16
Il ne faut pas modifier la version du plugin ici. La version du plugin est modifier uniquement lorsque l'on fait une release du plugin.

2022-08-25 07:57 UTC, f2cmbeapi commented on shoppingfeed.php
> + * Version:         6.1.16
Corrigé.

2022-08-25 14:47 UTC, petitphp submitted a review, later dismissed

2022-08-25 15:18 UTC, petitphp submitted a review, later dismissed

2022-09-06 10:29 UTC, petitphp approved these changes

2022-09-06 10:33 UTC, merged