Refacto feed parts generation, now add new as_schedule_single_action …
BeAPI/shoppingfeed-for-woocommerce pull request #54
Opened 2022-09-13 15:53 UTC by jeremykervran

…on incremented page

2022-09-13 19:11 UTC, petitphp requested changes
C'est bon dans l'ensemble, juste quelques points à corriger. Il faudrait aussi tester la génération avec cette branche pour voir si le résultats est conforme à ce que l'on génére aujourd'hui.

2022-09-13 19:11 UTC, petitphp commented on src/Feed/AsyncGenerator.php
> +			if ( ! empty( $option['currentPage'] ) && $option['currentPage'] === $total_pages ) {
Ici il faut utiliser `$page` au lieu de `$option['currentPage']`. On peut aussi supprimer les `{get/update}_option` au dessus qui sont obsolètes.

2022-10-19 14:35 UTC, petitphp approved these changes
J'ai fais des tests en local et j'ai corrigé un soucis avec le nombre d'arguments dans un `add_action` qui n'était pas à jour (+ quelques correction de style).

C'est fonctionnel pour moi.

2023-05-11 08:25 UTC, Rahe approved these changes

2023-08-21 10:09 UTC, merged