Added option to get variations with stock 0 in feed + new query
BeAPI/shoppingfeed-for-woocommerce pull request #57
Opened 2022-09-22 10:50 UTC by jeremykervran

Je pense qu'on a pas d'autre choix que de faire une query custom pour gérer les variations à stock 0 dans le flux, à cause du fonctionnement de base de WC qui base tout sur une option : https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-product-variable.html#source-view.302

Modifier cette option à la volée entrainerait trop d'effets de bords possibles.

Y'a potentiellement mieux que la WP_Query que je fais dans get_all_product_variations( $product ) - src/Products/Product.php ligne 454, en passant par une WC_Query peut-être ?

Mais en l'état ça marche : 

<variations>
    <variation>
        <reference>21</reference>
        <quantity>0</quantity> // STOCK A ZERO QUI REMONTE
        <price>10.00</price>
        <discounts>
            <discount type="price">8.00</discount>
        </discounts>
        <attributes>
            <attribute>
            <name>variation-1</name>
            <value>
            <![CDATA[ value variation 1 ]]>
            </value>
            </attribute>
        </attributes>
    </variation>
</variations>

2022-09-23 09:08 UTC, petitphp commented
Je vois que [`WC_Product_Variable::get_available_variations`](https://github.com/woocommerce/woocommerce/blob/5.1.0/includes/class-wc-product-variable.php#L289) appel en interne [`WC_Product_Variable::get_children`](https://github.com/woocommerce/woocommerce/blob/1d6a44ddb17fa4bbd17ecfcd03f5924219a22fcc/includes/class-wc-product-variable.php#L202) et filtre les éléments ensuite.

De notre côté, si la personne à choisis d'avoir toutes les variations même avec un stock à zéro on pourrait utiliser `WC_Product_Variable::get_children` pour récupérer les variations et faire les traitements ?

2022-10-07 07:52 UTC, Rahe requested changes

2022-10-07 07:52 UTC, Rahe commented on src/Admin/Options.php
> +                        name="<?php echo esc_html( sprintf( '%s[zero_stock_variations]', self::SF_FEED_OPTIONS ) ); ?>"
esc_attr et pas esc_html

2022-10-07 07:52 UTC, Rahe commented on src/Admin/Options.php
> +                        <?php echo esc_attr( $zsv_checked ); ?>
esc_html et pas esc_attr

2022-10-07 07:52 UTC, Rahe commented on src/Products/Product.php
> +		return is_array( $query->get_posts() ) ? $query->get_posts() : [ $query->get_posts() ];
Ya have_posts() pour vérifier qu'il ya des posts attachés à la query.

2022-10-07 07:52 UTC, Rahe commented on src/ShoppingFeedHelper.php
> +		if ( 'on' === $zero_stock_variations ) {
ça peut êrte fait avec un 
```
return 'on' === $zero_stock_variations;
```

2022-10-07 07:52 UTC, Rahe commented on src/Feed/Generator.php
> +				if ( empty( $sf_product->get_variations( true ) ) ) {
Faut stocker le résultat de `$sf_product->get_variations( true )` car là ya deux appels gratuits.

2022-10-17 17:19 UTC, petitphp reviewed
@jeremykervran Il faudrait qu'on se repose sur la PR pour voir. Je me demande si ça n'ajoute pas un effet de bord l'ajout du paramètre `$for_feed`.

2022-10-17 17:19 UTC, petitphp commented on src/Products/Product.php
> +	public function get_all_product_variations( \WC_Product_Variable $product ) {
Je ne vois pas où cette méthode est utilisée ?

2022-10-17 17:19 UTC, petitphp commented on src/Products/Product.php
> +		return $query->have_posts() ? $query->get_posts() : [ $query->get_posts() ];
C'est voulu de renvoyer un tableau avec `get_posts` si on a pas de posts ?

2022-10-17 17:19 UTC, petitphp commented on src/Products/Product.php
> +	public function get_variations( $for_feed = false ) {
Pourquoi avoir ajouter un paramètre à `get_variations` ?

2022-10-24 19:07 UTC, Rahe commented on src/Admin/Options.php
> +                        <?php echo esc_html( $zsv_checked ); ?>
ya la fonction `checked` de WP pour ça

2022-10-24 19:07 UTC, Rahe commented on src/ShoppingFeedHelper.php
> +		$zero_stock_variations = self::get_sf_feed_options( 'zero_stock_variations' );
Ça pourrait être sur une seule ligne

2023-01-09 14:21 UTC, petitphp commented on src/Admin/Options.php
> +			__( 'Show variations with stock 0', 'shopping-feed' ),
Je trouve le wording bizarre. Je changerais pour quelque chose comme "Include out of stock variations in the feed".

Il faudrait revoir les autres endroits où on utilise "zero_stock" pour "out_of_stock"

2023-01-10 08:37 UTC, petitphp commented on src/Products/Product.php
>  			$wc_product_variations = $product->get_available_variations();
Ici dans un cas la méthode retourne un tableau d'ids alors que l'autre retourne un tableau de données.

Dans le cas de `get_available_variations` il faut récupérer les valeurs des clés `variation_id`.

2023-01-10 08:42 UTC, petitphp commented on src/Products/Product.php
> +			$wc_product_variation  = new \WC_Product_Variation( $wc_product_variation['variation_id'] );
Ici, on peut utiliser directement `$wc_product_variation` qui est désormais un tableau d'ids.

2023-07-11 09:25 UTC, petitphp commented
TODO: rebase `develop`

2024-05-22 09:47 UTC, merged