WIP: put shopping feed API calls on product update as async
BeAPI/shoppingfeed-for-woocommerce pull request #69
Opened 2023-04-27 14:02 UTC by stephane-gillot

2023-04-28 10:50 UTC, jeremykervran approved these changes

2023-04-28 10:51 UTC, jeremykervran commented
@petitphp je veux bien ton avis aussi, même si tout me parait ok techniquement

2023-05-02 13:31 UTC, petitphp requested changes
@stephane-gillot Pour moi ce n'est pas la peine de créer une nouvelle classe. On peut tout laisser dans la classe `WoocommerceActions`.

Là, la classe `AsyncAPI` n'est jamais instanciée au démarrage du plugin.

2023-05-03 07:22 UTC, petitphp requested changes

2023-05-03 08:06 UTC, stephane-gillot commented on src/Admin/WoocommerceActions.php
> +			$inventory_update = new InventoryUpdate();
done

2024-01-04 15:44 UTC, closed without merging